### ISSUE TITLE
No files for downloading or update

### ISSUE THREAD

**Issue by vitkulov** [samebug/samebug-idea-plugin#1]
https://plugins.jetbrains.com/plugin/8174-samebug
An error occurs while loading the file:
[screenshot](http://i.imgur.com/lJcA6M7.jpg)

**Comment by progos** [comment]
Hi, 

I think it is an issue at JetBrains that will be fixed until Monday. Hopefully.

**Comment by vitkulov** [comment]
And can't install plugin manualy. (downloaded from here)
[screenshot](http://i.imgur.com/sbfy8eG.jpg)

**Comment by progos** [comment]
So you somehow managed to download it from JetBrains? It still looks unavailable for me.

**Comment by vitkulov** [comment]
No, I have download it from releases section here at this repo.
[samebug/samebug-idea-plugin](https://github.com/samebug/samebug-idea-plugin/releases)

**Comment by progos** [comment]
That's the source code.

**Comment by progos** [comment]
Download it from here:
https://drive.google.com/file/d/0B9nTrM5MwxzgX2Q2ckhiRVhDT0U/view?usp=sharing

I delete it when you downloaded.

**Comment by vitkulov** [comment]
Done.
Thank you!

**Comment by progos** [comment]
Cool. We welcome any issues, and ideas to improve it. Thanks for trying.

**Comment by poroszd** [comment]
For manual install, the plugin is still available at
https://jetbrains-plugins.s3.amazonaws.com/8174/34107/samebug-idea-plugin-0.14.3%2bidea.zip

JetBrains will fix the plugin repo on Monday, that will make the plugin available from Idea again.
